### ISSUE TITLE
스폰서 순서가 옳지 않은것 같습니다.

### ISSUE THREAD

**Issue by Nerd-Bear** [pythonkr/pyconkr-api#139]
![image](https://user-images.githubusercontent.com/26026903/62778073-44268700-baea-11e9-84df-274260b34630.png)
Gold 스폰서가 Silver 스폰서 위에 있어야 하는데 맨 아래 내려와 있습니다 🙏

**Comment by iiogmgo** [comment]
스폰서 등급이 기본 정렬 방법으로 리턴되어 생기던 문제였습니다. 해결되었습니다 :)
